containerPort: 10251
hostNetwork:
  enabled: true
replicas: 2
defaultArgs:
  - --cert-dir=/tmp
  - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
  - --kubelet-use-node-status-port
  - --secure-port=10251
  - --metric-resolution=15s
  - --kubelet-insecure-tls